version: "3.8"

services:
  olive-db:
    image: postgres:14-alpine
    container_name: olive-db
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - olive-network

  olive-server:
    image: luxcgo/olive:latest
    container_name: olive-server
    depends_on:
      - olive-db
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:4000:4000
    command:
      [
        "./olive",
        "server",
        "--db-host",
        "olive-db:5432",
        "-l",
        "/downloads",
        "-s",
        "/downloads"
      ]
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - ./downloads:/downloads
      - ./config:/config
    networks:
      - olive-network

  olive-portal:
    image: luxcgo/olive-portal:latest
    container_name: olive-portal
    depends_on:
      - olive-server
    ports:
      - "8080:8080"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - olive-network

networks:
  olive-network:
